export default {
    GLOBAL_SET_STATE: 'GLOBAL_SET_STATE',
    // App
    SET_CDN: 'SET_CDN',
    SET_PUSHSTATUS: 'SET_PUSHSTATUS',
    
    // TabBar
    SET_TABBAR: 'SET_TABBAR',
    
    // 授权
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    RECV_LOGIN: 'RECV_LOGIN',
    LOGOUT: 'LOGOUT',
    SET_AUTHORIZATION: 'SET_AUTHORIZATION',
    
    // 注册
    REQUEST_SIGNUP: 'REQUEST_SIGNUP',
    RECV_SIGNUP: 'RECV_SIGNUP',
    
    // 需求
    REQUEST_REQUIREMENT: 'REQUEST_REQUIREMENT',
    REQUEST_REQ_ADDING: 'REQUEST_REQ_ADDING',
    REQUEST_REQ_APPEND: 'REQUEST_REQ_APPEND',
    REQUEST_REQ_DETAIL: 'REQUEST_REQ_DETAIL',
    REQUEST_REQ_DISCUSSIONS: 'REQUEST_REQ_DISCUSSIONS',
    REQUEST_POST_DISCUSSION: 'REQUEST_POST_DISCUSSION',
    REQUEST_ORDERS: 'REQUEST_ORDERS',
    REQUEST_ORDERS_APPEND: 'REQUEST_ORDERS_APPEND',
    REQUEST_ORDER_ADD: 'REQUEST_ORDER_ADD',
    REQUEST_ORDER_DETAIL: 'REQUEST_ORDER_DETAIL',
    REQUEST_POST_JUDGEMENT: 'REQUEST_POST_JUDGEMENT',
    REQUEST_UPLOAD_AVATAR: 'REQUEST_UPLOAD_AVATAR',
    
    // 用户信息页
    REQUEST_OTHER_USER: 'REQUEST_OTHER_USER',
    REQUEST_USER_REQ: 'REQUEST_USER_REQ',
    REQUEST_USER_JUDGE: 'REQUEST_USER_JUDGE',
    
    RECV_REQ_DETAIL: 'RECV_REQ_DETAIL',
    RECV_DISCUSSIONS: 'RECV_DISCUSSIONS',
    RECV_ORDERS: 'RECV_ORDERS',
    RECV_ORDERS_APPEND: 'RECV_ORDERS_APPEND',
    RECV_ORDER_DETAIL: 'RECV_ORDER_DETAIL',
    
    RECV_OTHER_USER: 'RECV_OTHER_USER',
    RECV_USER_REQ: 'RECV_USER_REQ',
    RECV_USER_JUDGE: 'RECV_USER_JUDGE',
    
    INSERT_REQUIRMENT: 'INSERT_REQUIRMENT',
    LOAD_REQUIREMENT: 'LOAD_REQUIREMENT',
    LOAD_REQUIREMENT_APPEND: 'LOAD_REQUIREMENT_APPEND',
    FETCH_NEW_REQUIREMENT: 'FETCH_NEW_REQUIREMENT',
    
    CLR_REQ_DETAIL: 'CLR_REQ_DETAIL',
    CLR_ORDER_DETAIL: 'CLR_ORDER_DETAIL',
    CLR_DISCUSSIONS: 'CLR_DISCUSSIONS',
};
