export default {
    // App
    SET_CDN: 'SET_CDN',
    SET_PUSHSTATUS: 'SET_PUSHSTATUS',
    
    // TabBar
    SET_TABBAR: 'SET_TABBAR',
    
    // 授权
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    RECV_LOGIN: 'RECV_LOGIN',
    LOGOUT: 'LOGOUT',
    SET_AUTHORIZATION: 'SET_AUTHORIZATION',
    
    // 注册
    REQUEST_SIGNUP: 'REQUEST_SIGNUP',
    RECV_SIGNUP: 'RECV_SIGNUP',
    
    // 需求
    REQUEST_REQUIREMENT: 'REQUEST_REQUIREMENT',
    REQUEST_REQ_ADDING: 'REQUEST_REQ_ADDING',
    REQUEST_REQ_APPEND: 'REQUEST_REQ_APPEND',
    
    INSERT_REQUIRMENT: 'INSERT_REQUIRMENT',
    LOAD_REQUIREMENT: 'LOAD_REQUIREMENT',
    LOAD_REQUIREMENT_APPEND: 'LOAD_REQUIREMENT_APPEND',
    FETCH_NEW_REQUIREMENT: 'FETCH_NEW_REQUIREMENT',
    
};
